### ISSUE TITLE
Form fails to export with POSIXct error

### ISSUE THREAD

**Issue by SimpleAddress4390** [vubiostat/redcapAPI#10]
A long running routine has recently stopped working when extracting data from REDCap.  The code is unchanged, I am informed that the REDCap study is unchanged, although the data are always changing.

The following call results in the error. 
Error in as.POSIXct.numeric(records[[i]], format = "%Y-%m-%d") : 
  'origin' must be supplied

dataset <- as.data.frame(exportRecords(
   rcon,
   factors = FALSE,
   forms = f[i],
   records = subjectIDs,
   events = NULL,
   labels = FALSE,
   dates = TRUE,
   survey = TRUE,
   dag = FALSE,
   checkboxLabels = FALSE,
   colClasses = NA,
   batch.size = -1,
   bundle = getOption("redcap_bundle"),
   error_handling = getOption("redcap_error_handling"),
   form_complete_auto = TRUE)
)    

When the dates option is changed to FALSE, the error still shows, but the extract succeeds (and the resulting column is text).

I do see some dates field values with -5, -8 (study assigned values).  The date fields in REDCap have validation_type as "date_mdy".  Any ideas if this is a bug, data error, work arounds?

thanks!

**Comment by nutterb** [comment]
The date fields with -5, and -8 are the issue here. The standard REDCap export format for `date_mdy` is 'yyyy-mm-dd'. 

In order for the `as.POSIXct.numeric` to be applied, all of the date values in the column for your `subjectIDs` must be one of these numeric value, instead of the character mask. What we want to do is force these to be read as character vectors, even when they only contain numeric variable. This can be done with the `colClasses` argument. Something like

`colClasses = list([your_date_variable] = 'character')`

If you're not sure which variable is the offender, or you just want to be extra careful, this should build an object that will for all of the date variables to read as character. (I haven't tested this, it might needs some polish)

```
meta <- exportMetaData(rcon)
meta <- meta[grepl("^date", meta$field_type), ]
colClassArg <- replicate(length(meta$field_type), 
                         "character", 
                         simplify = FALSE)
names(colClassArg) <- meta$field_type
```

Out of curiosity, how are you getting -5 and -8 into these fields? Is this something the web interface allows, or are you using an import to assign those values?

**Comment by SimpleAddress4390** [comment]
Thank you for the response.  I'll try to build the object as you suggest.  I'm originally a SAS programmer and am winging my way into using R and APIs to get data from these systems.  

In answer to your curiosity:

I understand that REDCap allows you identify 'missing value' values for a field such as -5=something, -8=something else, etc.  The study does this on tons of fields on every study.  I am inclined to think -5 and -8 are not 'only themselves' the problem because they exist in other forms and on other projects with date fields.   Those forms and projects are working fine.

I think the issue is one I saw on other 'text' fields in REDCap where the API returns a numeric field if all the values are blank even if the validation_type in REDCap says 'text.'  In this case, the only values are a few -5, -8 so the API returns the field as an INT. (see screenshot).  This was when running dates=FALSE to allow the extraction to work.
![rstudio_566AL4ggbK](https://user-images.githubusercontent.com/7174635/223733233-072e0fd4-ee44-4ac7-a7d6-f64be567f345.png)

Previously the field values were entirely NA and the extracted dataset looked like this with the dates=TRUE:
![rstudio_erAcekXszf](https://user-images.githubusercontent.com/7174635/223733373-0cb6b23d-ced7-4774-8c3f-78bb713af953.png)

**Comment by SimpleAddress4390** [comment]
update: The study created a fake subject record and put a date in for each of the date_sample1, 2, 3 and 4 fields.  The export now works flawlessly with date=TRUE in the API call.  I will continue to try to apply the fixes nutterb suggested above, but at least I can export the upcoming analysis.  Thanks!!!!!!

![image](https://user-images.githubusercontent.com/7174635/223764459-e89f929f-6174-480d-99a5-a8fd79f4a3f6.png)

**Comment by SimpleAddress4390** [comment]
Thanks @nutterb 

The dummy record method probably can't be permanent because we can't keep fake data in the system.  I have been trying to code the example you gave me.  I hand-coded it to test and it worked with :

      colClasses =  list('date_sample1'='character', 'date_sample2'='character', 
                                  'date_sample3'='character','date_sample4'='character'),

I'm just trying to construct that type of list from the example using the metadata for any study.  I'll get there....

regards

**Comment by spgarbet** [comment]
The latest version added handlers which can be used to override date conversions for field types if this helps.

**Comment by spgarbet** [comment]
```
handlers=list('date_', function(x) {ifelse(sub(x,1,1) == "-", NA, as.Date(x))}
```

**Comment by SimpleAddress4390** [comment]
I updated to v 2.4.0 and the call looks like this:

dataset <- as.data.frame(exportRecords(
   rcon,
   factors = FALSE,
   fields = NULL,
   forms = "form_4_labs",
   records = subjectIDs,
   events = NULL,
   labels = FALSE,
   dates = TRUE,
   survey = TRUE,
   dag = FALSE,
   checkboxLabels = FALSE,
   handlers=list('date_', function(x) {ifelse(sub(x,1,1) == "-", NA, as.Date(x))}),
   colClasses = NULL,
   batch.size = -1,
   bundle = getOption("redcap_bundle"),
   error_handling = getOption("redcap_error_handling"),
   form_complete_auto = TRUE)
)    

The error message is the same:
Error in as.POSIXct.numeric(records[[i]], format = "%Y-%m-%d") : 
  'origin' must be supplied

is that 'date_' looking for validation_type values of date_mdy?  Or is it looking variable names with 'date_' ?  or do I need to construct a vector "date_sample1","date_sample2","date_sample3","date_sample4")  and pass in place of 'date_' ?

thanks

**Comment by SimpleAddress4390** [comment]
With respect to the colClasses approach...
if this works:
   colClasses = list('date_sample1','date_sample2','date_sample3','date_sample4'='character'),

how would I construct that var list from a vector?  I tried this:
   dtVect <- c("date_sample1","date_sample2","date_sample3","date_sample4")
   dtList <- toString(dQuote(dtVect, FALSE))


> dtList
[1] "\"date_sample1\", \"date_sample2\", \"date_sample3\", \"date_sample4\""

This fails:
   colClasses = list(dtList='character'),

**Comment by nutterb** [comment]
> I updated to v 2.4.0 and the call looks like this:
> 
> dataset <- as.data.frame(exportRecords( rcon, factors = FALSE, fields = NULL, forms = "form_4_labs", records = subjectIDs, events = NULL, labels = FALSE, dates = TRUE, survey = TRUE, dag = FALSE, checkboxLabels = FALSE, handlers=list('date_', function(x) {ifelse(sub(x,1,1) == "-", NA, as.Date(x))}), colClasses = NULL, batch.size = -1, bundle = getOption("redcap_bundle"), error_handling = getOption("redcap_error_handling"), form_complete_auto = TRUE) )
> 
> The error message is the same: Error in as.POSIXct.numeric(records[[i]], format = "%Y-%m-%d") : 'origin' must be supplied
> 
> is that 'date_' looking for validation_type values of date_mdy? Or is it looking variable names with 'date_' ? or do I need to construct a vector "date_sample1","date_sample2","date_sample3","date_sample4") and pass in place of 'date_' ?
> 
> thanks

I think we gave you a malformed `handlers` argument. Try this one instead. (notice the `[validation_type] = [function]` syntax here instead of `[validation_type], [function]`. 

```
handlers = list(date_ = function(x) {ifelse(sub(x,1,1) == "-", NA, as.Date(x))}
```

**Comment by nutterb** [comment]
> dtVect <- c("date_sample1","date_sample2","date_sample3","date_sample4")

```
dtVect <- c("date_sample1","date_sample2","date_sample3","date_sample4")

classList <- replicate(length(dtVect), 
                        "character", 
                        simplify = FALSE)
names(classList) <- dtVect
```

Then use `colClasses = classList`

**Comment by spgarbet** [comment]
Where did we land on this? @SimpleAddress4390 have you gotten it working?

**Comment by SimpleAddress4390** [comment]
I was able to get the @nutterb example working using the metadata for each form as I extract it.  I have not tried the handler method again.

**Comment by spgarbet** [comment]
I now understand the full depth of this problem. I had an epiphany working on #14. I see this as the single most important thing to fix. I have a design that will require some work, but I should be done in a few days.

**Comment by spgarbet** [comment]
Proposed code fix to fieldToVar (pseudocode)

```
# Regex syntax check
# https://mkyong.com/regular-expressions/how-to-validate-date-with-regular-expression/
# https://stackoverflow.com/questions/7536755/regular-expression-for-matching-hhmm-time-format
"date_"     = "[0-9]{1,4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"
"datetime_" = "[0-9]{1,4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])\\s([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]"
"datetime_seconds_" = "[0-9]{1,4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])\\s([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]"
"time_mm_ss" = "[0-5][0-9]:[0-5][0-9]"
"time_hh_mm_ss" = "([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]"
"time" = "([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]"
"float" = "[-+]?(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))([Ee][+-]?[0-9]+)?"
"number" = "[-+]?(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))([Ee][+-]?[0-9]+)?"
"calc" = "[-+]?(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))([Ee][+-]?[0-9]+)?"
"int" = "[-+]?[0-9]+"
"integer" = "[-+]?[0-9]+"
"select" = NA
"radio" = NA
"dropdown" = NA
"yesno" = "[01]"
"truefalse" = ???
"checkbox" = ??? 0, 1, Checked, Unchecked, checked, unchecked
"form_complete" = "[012]"

nas    <- apply(records, 2, function(x) is.na(x) | x=='')
syntax <- mapply(function(x, pt) !nas & grepl(pt,x), records, regexs[meta_data$field_type])
good   <- !nas & !syntax
records <- typecast(records, good, meta_data)
```

**Comment by nutterb** [comment]
I think for int I would recommend `"^[-+]?[0-9]+(|\\.|\\.[0]+)$"` as the regex.  It should match the forms ending in a decimal and those that have only 0's after the decimal.

```
x <- c("1", "1.", "1.0", "1.3", "123", "-1", "+1", "+1.2", "1.00000", "1.003", "451234")
names(x) <- x
res <- grepl("^[-+]?[0-9]+(|\\.|\\.[0]+)$", x)
names(res) <- x
res
      1      1.     1.0     1.3     123      -1      +1    +1.2 1.00000   1.003  451234 
   TRUE    TRUE    TRUE   FALSE    TRUE    TRUE    TRUE   FALSE    TRUE   FALSE    TRUE
```

For true/false, I think we want "(0|1|true|false)"

for true/false, this should work "^(?i)(0|1|true|false)$", but would require trimming whitespace before using (the ?i) makes the match case-insensitive)

yes/no could be "^(?i)(0|1|yes|no)$". (the addition to what you have would make it work for validating import as well

radio, dropdown, and checkbox would want to have the field codes shaped into a (choice1|choice2|...|choicen) type list

**Comment by spgarbet** [comment]
This proposed overhaul will hopefully deal with this issue: https://github.com/nutterb/redcapAPI/issues/15

It would be good to consider NA class types as well versus the metadata.

**Comment by spgarbet** [comment]
I had something in mind more like this the following. The biggest thing is to get rid of a lot of TRUE/FALSE parameters and just make them callback lists for the processing loop. The processor lists can be switched for the options desired. Provide multiple callback options and a sensible default.

## Arguments

* `rcon`: a `redcapApiConnection` object.

### Limiters 

* `fields`: A vector of field names to export. Ignored if length = 0.
* `drop_fields`: A vector of field names to remove from the export. Ignore if length = 0.
* `forms`: A vector of form names. If length > 0, the fields on the listed forms will be included in the export (the union of these fields with those in `fields`).
* `events`: A vector of events names for which records will be exported.
* `records`: A vector of record IDs for which data will be exported.
* `survey`: `logical(1)`. When `TRUE`, survey related fields will be exported. Defaults to `FALSE`
* `dag`: `logical(1)`. When `TRUE`, the `redcap_data_access_group` field will be exported. Defaults to `FALSE`.
* `date_begin`: `POSIXct(0/1)`. Ignored if length = 0 (default). Otherwise, records created or modified after this date will be returned.
* `date_end`:`POSIXct(0/1)`. Ignored if length = 0 (default). Otherwise, records created or modified before this date will be returned.

### Processor Specification

* `csv_delimiter`: One of `c(",", "\t", ";", "|", "^")`. Designates the delimiter for the CSV file received from the API.
* `na` : `list`. A list of overrides for the determination of NA for a field_type.
* `validation` : `list`. A list of overrides for the default validations for a field_type.
* `casting` : `list`. A list of overrides for type conversions.
* `label`: `function`. When not null, variable labels are added as an attribute to the vectors by calling the given function. Defaults to a function that strips HTML and UNICODE.
* `...`: Arguments to pass to callback methods specified in `na`, `validation`, `casting`, `label`.

### Bonus 

Note: really should just be a post process modification--outside scope of function. We could provide this as a transform function. 

* `mchoice`: `logical(1)`. When `TRUE` (default), if the `Hmisc` package is loaded, checkbox variables will be added to the end of the data with options coded as `Hmisc:mChoice` objects. This will be forced to `FALSE` if `Hmisc` is not on the search path (redcapAPI will not load Hmisc for you)

Then return the validation report as an attribute "problems" on the resulting data.frame returned.

The override list keys are as follows: `date_, datetime_, datetime_seconds_, time_mm_ss, time_hh_mm_ss, time, float, number, calc, int, integer, select, radio, dropdown, yesno, truefalse, checkbox, form_complete, sql`

If in the future REDCap adds more keys, a user can easily add it in the processor lists and the package would still function. Some of these rely on information not available until the meta data is processed for that field. This will be made available to the respective functions. This callback method allows the user to do any number of things relating to internationalization as well. One could use -5 as an NA value. Maybe also pass the field_name to the function if they want to write specific handling for a specific field name they can.

**Comment by spgarbet** [comment]
This leads to something like the following:

```


isNAorBlank <- function(x, field_name, ...) is.na(x) | x==''

na <- list(
  date_              = isNAorBlank,
  datetime_          = isNAorBlank,
  datetime_seconds_  = isNAorBlank,
  time_mm_ss         = isNAorBlank,
  time_hh_mm_ss      = isNAorBlank,
  time               = isNAorBlank,
  float              = isNAorBlank,
  number             = isNAorBlank,
  calc               = isNAorBlank,
  int                = isNAorBlank,
  integer            = isNAorBlank,
  select             = isNAorBlank,
  radio              = isNAorBlank,
  dropdown           = isNAorBlank,
  yesno              = isNAorBlank,
  truefalse          = isNAorBlank,
  checkbox           = isNAorBlank,
  form_complete      = isNAorBlank,
  sql                = isNAorBlank
)


val_rx <- function(rx) { function(x, field_name, ...) grepl(rx, x) }
val_choice <- function(x, field_name, coding, ...) grepl(paste0(choice,col='|'), x) 

validation <- list(
  date_              = val_rx("[0-9]{1,4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])"),
  datetime_          = val_rx("[0-9]{1,4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])\\s([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]"),
  datetime_seconds_  = val_rx("[0-9]{1,4}-(0?[1-9]|1[012])-(0?[1-9]|[12][0-9]|3[01])\\s([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]"),
  time_mm_ss         = val_rx("[0-5][0-9]:[0-5][0-9]"),
  time_hh_mm_ss      = val_rx("([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]"),
  time               = val_rx("([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]"),
  float              = val_rx("[-+]?(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))([Ee][+-]?[0-9]+)?"),
  number             = val_rx("[-+]?(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))([Ee][+-]?[0-9]+)?"),
  calc               = val_rx("[-+]?(([0-9]+\\.?[0-9]*)|(\\.[0-9]+))([Ee][+-]?[0-9]+)?"),
  int                = val_rx("^[-+]?[0-9]+(|\\.|\\.[0]+)$"),
  integer            = val_rx("[-+]?[0-9]+"),
  yesno              = val_rx("^(?i)(0|1|yes|no)$"),
  truefalse          = val_rx("(0|1|true|false)"),
  checkbox           = val_rx("^(?i)(0|1|yes|no)$"),
  form_complete      = val_rx("[012]"),
  select             = val_choice,
  radio              = val_choice,
  dropdown           = val_choice,
  sql                = val_choice # This requires a bit more effort !?
)


# Can be sent to both validation and cast for raw output!
raw <- list(
  date_              = NA,
  datetime_          = NA,
  datetime_seconds_  = NA,
  time_mm_ss         = NA,
  time_hh_mm_ss      = NA,
  time               = NA,
  float              = NA,
  number             = NA,
  calc               = NA,
  int                = NA,
  integer            = NA,
  yesno              = NA,
  truefalse          = NA,
  checkbox           = NA,
  form_complete      = NA,
  select             = NA,
  radio              = NA,
  dropdown           = NA,
  sql                = NA,
)

cast.POSIX <- list(
  date_              = function(x, ...) as.POSIXct(x, format = "%Y-%m-%d"),
  datetime_          = function(x, ...) as.POSIXct(x, format = "%Y-%m-%d %H:%M"),
  datetime_seconds_  = function(x, ...) as.POSIXct(x, format = "%Y-%m-%d %H:%M:%S"),
  time_mm_ss         = function(x, ...) chron::times(paste0("00:",x), format=c(times="h:m:s")),
  time_hh_mm_ss      = function(x, ...) chron::times(x, format=c(times="h:m:s")),
  time               = function(x, ...) chron::times(gsub("(^\\d{2}:\\d{2}$)", "\\1:00", x), 
                                                     format=c(times="h:m:s")),
  float              = as.numeric,
  number             = as.numeric,
  calc               = as.numeric,
  int                = as.integer,
  integer            = as.numeric,
  yesno              = function(x, coding, ...) factor(x, levels=coding, labels=coding),
  truefalse          = function(x, ...) x == 'true',
  checkbox           = function(x, coding, ...) factor(x, levels=coding, labels=coding),
  form_complete      = function(x, coding, ...) factor(x, levels=coding, labels=coding),
  select             = function(x, coding, ...) factor(x, levels=coding, labels=coding),
  radio              = function(x, coding, ...) factor(x, levels=coding, labels=coding),
  dropdown           = function(x, coding, ...) factor(x, levels=coding, labels=coding),
  sql                = function(x, coding, ...) factor(x, levels=coding, labels=coding)
)

```

**Comment by spgarbet** [comment]
A user just wanting "date_" to come back as Date would be like this:
```
data <- exportRecords(rcon, cast=list(date_ = as.Date))
```

The default lists are merged with the user specified lists, with the user's taken precedence.

**Comment by nutterb** [comment]
I'm catching on to your vision, and I'm on board with it. Some clarifying questions:

1. Batching? Your argument list doesn't include an argument for `batch_size`. We know there are limits to how much a call can pull, and those limits are often outside the ability of the user to control. Is this a feature you are wishing to include?
2. Raw or Labelled data? If not for the existence of SQL fields, we could get away with only pulling raw data or only pulling labelled data. This would have made a great deal of simplicity in dealing with multiple choice fields. Unfortunately, I don't see any mention of these types of fields in the API documentation and it would appear that the only way to get the raw data is with the API parameter `rawOrLabel = raw`, and the labelled values with `rawOrLabel = label`. Some options:
    + Only pull raw data. If there is a sql field, we execute a second call that retrieves only the record identifiers and the sql fields. We then merge them to the rest of the data. We could even, assuming we pull both raw and labelled this way, build our own dictionary to code into the select_choices_or_calculations property of the data dictionary. The limitation on this is that we would only be able to map between codes and labels that exist in the data, which may be a limiting factor on future imports.
    + Add an argument that permits the user to pull raw or labelled data and then train the processors to recognize both forms.
3. Your `cast` argument provides overrides for field types. Will this also handle field names, or does there need to be another argument to override defaults for a specific field?
4. I'm skeptical about using `...` to pass other arguments to `na`, `validation`, `cast`, and `label`. My experience is that using the dots works well if you're passing arguments to one other function, but it can get pretty messy if you try to pass arguments to multiple functions. What strategies have you used to manage these situations? 
5. Your defaults for multiple choice variables convert them to factors. What's the attitude toward factors around your user base?  There's a fairly broad antagonism toward factors in the R community, with many preferring to store them as characters. Most analyses that need factors will convert them on the fly anyway. Is there a way to poll your user base for a preference?

**Comment by spgarbet** [comment]
I'm reading through all the cases on #2. Bottom line is there should be overrides that supports all of these, and the only question is what is the default?

I have a love/hate relationship with your idea on 5. It does solve the factor question across the board. I've also have been left scratching my head trying to find a hidden option many times leading to frustration. 

Another stray idea: we keep the old exportRecords and just have a new function name for the breaking one for a period of time.

**Comment by nutterb** [comment]
The more I think on it, the more I move toward disliking storing factor on rcon. It's an easy solution, but not necessarily good. 

I missed your earlier suggestion about scrapping `...`. The dots are a requirement of method dispatch so we'd have to abandon that. I'm not opposed to it, but since you've talked about maybe making a redcapColaConnection object, that should be taken into consideration. 

Keeping `exportRecords` isn't as stray an idea as you might think. That same idea is buried somewhere in the gargantuan amount of writing I did in my markdown document ([updated as a human readable format here](https://github.com/nutterb/redcapAPI/blob/issue-10-exportRecords-nutter/vignettes/DesignSpecification.md). I know it's a lot. Unfortunately for everyone who isn't me, writing is how I make sense of my world). I'd suggest discontinuing development on exportRecords, deprecate it, and then convert it to a function that adheres to the arguments of the API method (by default, it would spit out raw data and would only do any formatting based on what the API method returns). 

For this function, I'd suggest `exportRecordsFormatted` or `exportRecordsProcessed`

My very last idea: how about providing a set of helper functions that can be modified to process data. Specifically, we could provide a parent-function that returns a child-function. The arguments passed to the parent-function modify the behavior of the child-function. In the example below, I create a function called `formatCheckbox` which doesn't actually format a checkbox; it just allows you to customize the default arguments of a function that _will_ let you format the checkbox.

By default, I have it set to map 0 = Unchecked, and 1=Checked. And if I want to change it to return 0="" and 1="CheckboxLabel", I can do 

```
cast = list(checkbox = formatCheckbox(to_method = "label")
# OR
cast = list(checkbox = formatCheckbox(to_method = "label", 
                                      factor = TRUE) # to return as a factor
```
As it stands now, though, I think this is a good framework. 

```
library(redcapAPI)
records <- 
  data.frame(
    checkbox___a = sample(c("0", "1"), 10, replace = TRUE), 
    checkbox___b = sample(c("0", "1"), 10, replace = TRUE), 
    checkbox___d = sample(c("0", "1"), 10, replace = TRUE)
  )

records
#>    checkbox___a checkbox___b checkbox___d
#> 1             0            0            1
#> 2             1            0            1
#> 3             0            0            0
#> 4             0            1            0
#> 5             0            0            1
#> 6             0            1            1
#> 7             1            0            1
#> 8             0            0            0
#> 9             1            0            0
#> 10            0            0            1

select_choices <- "a, Backpacking | b, Canoeing | d, Cycling"

formatCheckbox <- function(to_method = c("custom", "coded", "label"),
                           from_unchecked = c("0"), 
                           from_checked = c("1"), 
                           to_unchecked = c("Unchecked"), 
                           to_checked = c("Checked"), 
                           factor = FALSE){
  to_method <- checkmate::matchArg(x = to_method, 
                                   choices = c("custom", "coded", "label"))
## Define a function to format checkbox based on parent inputs -----------------------
  function(x, 
           field_name, 
           choices, 
           mtd = to_method, 
           from_unchk = from_unchecked, 
           from_chk = from_checked, 
           to_unchk = to_unchecked, 
           to_chk = to_checked, 
           fctr = factor){
# Extract the field mapping
    field_choice <- sub("^.+___", "", field_name)
    mapping <- fieldChoiceMapping(choices)
    mapping <- mapping[mapping[, 1] == field_choice, ]

# If using coded or labeled output, set the value of the resulting unchecked and checked results
    if (mtd == "coded"){
      to_unchk <- ""
      to_chk <- mapping[1]
    } else if (mtd == "label"){
      to_unchk <- ""
      to_chk <- mapping[2]
    }
    
# Get indices of records that are checked, unchecked, or missing ---------------------
    x_unchecked <- which(x %in% from_unchk)
    x_checked <- which(x %in% from_chk)
    x_miss <- which(!x %in% c(from_unchk, from_chk))
    
# Set the output values -----------------------------------------------------------------
    x[x_unchecked] <- rep(to_unchk, length(x_unchecked))
    x[x_checked] <- rep(to_chk, length(x_checked))
    x[x_miss] <- rep(NA, length(x_miss))
    
# Make it a factor -----------------------------------------------------------------------
    if (fctr){
      x <- factor(x)
    }
    
    x
  }
}


records$checkbox___a <- 
  formatCheckbox(to_checked = "Selected", 
                 to_unchecked = "Not picked")(x = records$checkbox___a, 
                                              field_name = "checkbox___a", 
                                              choices = select_choices)
records$checkbox___b <- 
  formatCheckbox(to_method = "coded", 
                 to_checked = "Selected", 
                 to_unchecked = "")(x = records$checkbox___b, 
                                    field_name = "checkbox___b", 
                                    choices = select_choices)
records$checkbox___d <- 
  formatCheckbox(to_method = "label")(x = records$checkbox___d, 
                                    field_name = "checkbox___d", 
                                    choices = select_choices)

records
#>    checkbox___a checkbox___b checkbox___d
#> 1    Not picked                   Cycling
#> 2      Selected                   Cycling
#> 3    Not picked                          
#> 4    Not picked            b             
#> 5    Not picked                   Cycling
#> 6    Not picked            b      Cycling
#> 7      Selected                   Cycling
#> 8    Not picked                          
#> 9      Selected                          
#> 10   Not picked                   Cycling
```

**Comment by spgarbet** [comment]
The current version on branch issue-10 is getting close. It's got call backs, and should solve the following issues when complete: #24, #25, #35, #40, #45, #46

**Comment by spgarbet** [comment]
This is getting very close. The test suite build out is all that remains. Sooooon.

**Comment by spgarbet** [comment]
@SimpleAddress4390 This has proven to be a core issue in the library with a lot of related issues and if you want to try out the issue-10 branch and `exportRecordsTyped` it is a good time for feedback.

**Comment by spgarbet** [comment]
See `exportRecordsTyped` for the fix.
