### ISSUE TITLE
exportRecordsTyped bulk environment pull

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#106]
`rccola` had a means to execute a command over every possible connection in an environment. This was very useful to folks when they had to do processing on multiple redcap projects data all at once. The current design has added a means to open multiple connections. Should we add support for "bulk" operations over exports contained in a single environment? This would require a lot of modifications to existing post processing to detect if they were given an environment versus a data.frame. Overall a lot of work. All existing post processors would have to be S3 dispatched to Records or environments, and environments would loop back over records. 

Or maybe allow users to specify their own function to the `rccola` inner loop and expose that and just put that in the power users hands. This is probably the better approach--far less work and more extensible To accomplish this:

* Expose inner rccola loop to user.
* Put the `assign` parameter back in the loop. 

Aside: I'm continually surprised by some of the use cases I'm seeing. This one is a very inventive one.

**Comment by nutterb** [comment]
Inventive, indeed. I'm not sure I'm capturing the vision of what they are trying to do. (questions are meant to express curiosity, not skepticism)

What's the naming convention for Records objects, for example, if I have two connections open in an environment?

What's the advantage of putting the connections into a separate environment instead of into a list?

Is it something like this, but black boxed into an environment?
```
library(dplyr)
library(Hmisc)
library(redcapAPI)

url <- "https://redcap.vanderbilt.edu/api/"

RedcapData <- 
  data.frame(project_identifier = c('TestRedcapAPI', 'RepeatInstrumentEvent')) %>% 
  mutate(rcon = 
           lapply(project_identifier, 
                  function(pi){
                    redcapConnection(url = url, 
                                     token = keyring::key_get('redcapAPI', pi, 'API_KEYs'))
                  }), 
         Records = lapply(rcon, exportRecordsTyped), 
         Records = mapply(mChoiceCast, 
                          Records, 
                          rcon))
```

**Comment by spgarbet** [comment]
That is close. The end result is 4 related REDCap projects in a single environment. They they use lapply to apply things like mChoice across all of them.

**Comment by spgarbet** [comment]
One could do the same thing with a list just as easily.

**Comment by obregos** [comment]
Export forms separately, it is not reasonable for the decoupling of forms to be done post processing.  That needs to be handled up front as drinkRedcap was able to do (though in an environment that a 1-line of code converts to a list of data frames).  Whatever methods are used need to take into account the REDCap form structure.

**Comment by spgarbet** [comment]
@obregos @nutterb Had some time to work on this. I don't think this is a can of worms we want to open and introduce to the redcapAPI library. I wanted to pull some key management down into redcapAPI, ala rccola. The problem is that messing with environments in rccola confused a lot of users and I'm still addressing the mess that caused. Some users loved it, some didn't. Savannah has an idea for a post processing function that splits out the forms into a list. I think that is potentially a better approach. I'll open a separate ticket to discuss. 

## Thoughts

If I opened up the key management here and left out the complex autoassign. rccola could be adapted to the new functions and continue to provide the complexity. This is the "offload" this from the API library all together approach. I'm reticent about this, as key management is important and should be part of redcapAPI. 

Maybe we could drop all "assign" from the unlockREDCap function. It would be a lot easier to test, it wouldn't confuse users. Or better yet, use the assign as a specified environment. This is complicated because sometimes a function might have multiple things it returns. This would force a decision like "if a function returns a list and assign is specified then expand the list into the assign environment". With no assign one would get back the list, or maybe list of lists. 

The downside of all this assign is users did really crazy things like create environments to capture it, then unwind it back. Thus explicit code to unwind what was meant to help. 

## User Request

`rccola` provided a single call to export records. If forms was specified for a key name it would loop and call multiple times with the "form" argument and assign those back to "keyname.form" in the environment. Then a user would loop over everything in the environment and apply post transforms in bulk. One example I've seen had 4 REDCap databases and something like 20 forms in one of them and 4 in another. 

What is desired is someone to do the key management, assignment and post transforms in bulk in a similar manner. I could just port the rccola interface over, but given the problems so far I want to get this really direct and a proper solution. 

## Proposal

Revise unlockREDCap in the following manner:
* `assign` is optional and can used to specify an environment to write the output of each call. If not specified the function returns a list. 
* Expose the function that is called for power users to specify a function.
* The "forms" problem is still an issue. If the assign is passed down, the called function could do assignment in the same manner and we can provide the "exportRecordsTyped" call as before. !?

Then attempting to write pseudo-code I'm very frustrated by all this and think the 'unlockREDCap' function is all that is needed. The connections all map to API_KEYs 1-to-1 making it really clean in usage. The crypto key thing is done at that point. Maybe what's really needed is a separate loop function. `bulkExportTyped` ? 

Obviously this requires deeper thought on the issue.

**Comment by nutterb** [comment]
You might be happy to know that you're not the only one that gets frustrated thinking about this. It's taken me a while to come around to managing multiple connections as being particularly useful[1]. But even though I've been coming to grips with the idea, I'm kind of with you--I don't think managing environments is within the scope of what makes sense for redcapAPI to do. My poorly informed opinion is that it is likely better to provide a useful tool that users can utilize in whatever environment they choose. 

With that in mind, I think you're on the right track with `bulkExportTyped`, except I think that might be too specific. What would you think of a `redcapApply` function with the interface 

```{r}
redcapApply(rcon,   # A list of redcapConnections, 
            FUN,    #A function to apply to the connections, 
            ...)    # Additional arguments to pass to FUN
```
At its core, it could just be a wrapper for lapply, but give us the option to control the element names such at they have a naming convention of [connection_name].[function_name].  (@obregos 's notion of a function to export by form complicates this, as it would want to return a list of lists, but that's something we can figure out how to handle)

After the `redcapApply`, applying transformations and post processing functions is a simple matter of `lapply`[2] that the user can direct in whatever environment they wish. (for the convenience of such power users, leaving the ability to assign the connections to an environment in `unlockREDCap` is a nice gesture). 


1. It's kind of judgmental, but the use of multiple projects being needed gives me the feeling of a project design gone awry. While I understand that things go awry, I can't shake the feeling that there was a strategy that worked well in one instance of things going awry, and it's being assumed that it will work just as well in all the other ways things can go awry. I don't want to get sucked into a trap of writing a tool that people rely on to make up for improper planning and study design.
2. I'm having an afterthought now that it may not be as simple as lapply, as the connection objects have to be passed with many of the casting functions. The object returned by redcapApply might need to be classed so that there can be a `redcapApply.list` and `redcapApply.redcapList` (or something) so that we can distinguish between initial and subsequent calls.  It isn't perfect, but it's an ide.

**Comment by spgarbet** [comment]
My thoughts right now are:

* back off messing with environments in unlockREDCap. Have an assign parameter if someone wants to use them. 
* Split off the bulk records/form pull into a helper function and have a similar assign parameter.

This leaves unlockREDCap as the only function working with a keyring. Then a single specification can pull all the databases and/or forms into a list or environment. Clean separation of concerns. 

The apply construction is left for the user.

**Comment by spgarbet** [comment]
@nutterb Interesting bug discovery. I changed the test cases to all use the same connection. It looks like the metadata or other cached pieces are getting out of sync post changes from functions. This now causes the test stack to crash in a lot of ways.

This means the scope of this ticket just got much larger as now we can identify which functions need to resync the cached data to keep things working.

**Comment by spgarbet** [comment]
Well maybe not. The error seems to be a NULL arm

```
Error (test-04-fieldnames.R:5:1): (code run outside of `test_that()`)
Error in `devtools::test()`: 1 assertions failed:
 * Variable 'arms': Must be of type 'character', not 'NULL'.
Backtrace:
 1. redcapAPI::purgeProject(rcon, purge_all = TRUE)
      at test-04-fieldnames.R:5:0
 2. redcapAPI:::purgeProject.redcapApiConnection(rcon, purge_all = TRUE)
      at redcapAPI/R/purgeRestoreProject.R:169:2
 4. redcapAPI:::deleteArms.redcapApiConnection(...)
      at redcapAPI/R/deleteArms.R:50:2
 5. checkmate::reportAssertions(coll)
      at redcapAPI/R/deleteArms.R:93:2
```

**Comment by spgarbet** [comment]
Please review the previous commit. This seems to have fixed the issue.

**Comment by nutterb** [comment]
I'm surprised you got a NULL back from rcon$arms(). I thought we had written that to return a 0-row data frame if arms weren't available. Looks like there's some edge case we missed. 

This is a reasonable safeguard against the issue, though. If the API is returning NULL from exportArms, then deleteArms isn't going to anything productive. I would expect this to work pretty well.

......Running tests.....

And yup, it's passing tests on a clean session for me.

**Comment by spgarbet** [comment]
Here's my proposal: https://gist.github.com/spgarbet/650b88332ca867e3f0ec087f31cc59e5

**Comment by spgarbet** [comment]
Pull request #121
