### ISSUE TITLE
isNAorBlank

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#137]
Should we include "NA" as a string as a definition of NA? Users are already seeing fields that are "NA" in their invalid report for casting.

**Comment by berryld1** [comment]
This made me remember – missing data codes!

 
![image](https://github.com/vubiostat/redcapAPI/assets/116016336/fbd2929a-70a4-486d-b915-175a7f254a48)


This is quite tricky because there are a stock set -but also you can make up your own – like CBD here, which this project wanted (I think because they found it amusing).

Maybe we need an argument to specify any missing data codes being used, and let those validate?

If you’re setting x[is.na(x)] to empty string – then I think missing data codes would be the only NA (string “NA”) coming through to even be detected as invalid—does that sound right?

To make it even more complicated… action tag @NOMISSING in field_annotation means missing data codes are NOT valid for the field thus tagged– so, in that case, missing data codes (in an ideal world) would still evaluate as invalid.

**Comment by spgarbet** [comment]
In the call if you do the following:

na = function(x) is.na(x) | x=='' | x=='NA' | x=='CBD', 

This will cover these other codes. All this does is exclude these from the "invalid" report.  The action **@nomissing** tag is interesting. We may have to modify the invalid report to include these.

**Comment by berryld1** [comment]
Ah! Beautiful. Then you've already got it covered for missing data codes - so I would leave as-is for how the validations are working - with the exception of that @NOMISSING tag

**Comment by spgarbet** [comment]
[This ](https://github.com/vubiostat/redcapAPI/commit/df18dfab7dc27b86821402d3b4f99bb8cfb6226e) would allow a definition of 

```
na=function(x) is.na(x) | x=='' | x=='NA' | x=='CBD'
```

To apply to all fields.

**Comment by spgarbet** [comment]
@nutterb thoughts?

**Comment by nutterb** [comment]
It feels a little like giving someone a band aid for a nose bleed. If we start this now, we might be giving out a lot of band aids before the bleeding stops.

I think if we frame the problem such that 

1. Users are inputting a value to indicate when a field is deliberately left incomplete (this is admirable)
2. Our codebase is extremely rigid in how to handle these user-devised missing codes
3. There is no end to what users might throw at us: NA, N/A, na, 88...

I'm inclined to pull out the RhinoRocket (TM).

```
isNAorBlank <- function(missing_code = get option("redcap_missing_code", NULL)){
  function(x, ...){
    is.na(x) | x %in% c("", missing_code)
  }
}
```

This gives the ability to the user to extend the missing codes as far as they want/need. 

I know you're not a fan of options, but this is a place where the option makes it possible to set these codes globally when working with multiple projects or calls.

And as you noted, making it apply across all field types would be a matter of

options(redcap_missing_code = c("NA"))

**Comment by spgarbet** [comment]
Hm, interesting idea. Thought Lynne?

**Comment by berryld1** [comment]
Seems good to me - but you guys are so far above my head on good coding practices, I certainly can't speak to that.
Question - this same validation runs on the imports, too, right? So I would be able to import, say, an "NA" as a missing data code without getting that value removed from the import with these changes in place?
It's weird because I need to update a production database per a client request in a way that would lose data without a data transformation, so I'm testing the transformation and dumping into my dev instance, which has the updates implemented. I got a few warnings on invalid values ("NA") on the way out of prod (you saw those, Shawn)- and *many* more on the way into dev. Checking a few of these manually, they do seem to be string "NA"s, so interesting they didn't get dropped on the way out? That's unexpected, right, that they would get booted going in, but not going out?
Shawn, would you be kind enough to remind me how to use "attr" to find the fields/values, and I can see if I'm making stuff up, or, it not, send to you guys.

**Comment by berryld1** [comment]
Strike that!

**Comment by berryld1** [comment]
The export you and I looked at was only for the one form that needed the transformations - then I pulled the rest of the data, too, to dump in prod b/c I also need to script a report and want to script against the new structure.
Still, Shawn, how to use "attr" to look at these, please? :)

**Comment by spgarbet** [comment]
Yeah, we're going to have to do something. Benjamin is recommending an option, I was recommending a function override. 

`attr(data, "invalid")` to view at prompt. To embed in an Rmarkdown document:

````
```{r}
knitr::asis_output(format(attr(Records, "invalid")))
```
````

**Comment by berryld1** [comment]
attr(data, "invalid") - got it for the export, thank you!
is there anything returned from an import that would have same, i.e., can I do, dat <- importRecords(rcon=, data=), and that would have the attributes on it for the imported data?

**Comment by spgarbet** [comment]
I don't know for the import side. @nutterb ?

I spend a fair bit of time thinking about this last night. The idea to use option creates a complexity for the user in knowing about it, and from a type theory perspective embeds processing in a system monad which should be avoided. The other idea of allowing a function to be passed moves the routine from a static type to a dependent type, and this invokes a complexity that is also best to be avoided. I did however, think of a simple solution that requires little effort--just have a helper function that constructs the na list from a single function. In type theory, everything remains static and  you just have one potential function in the mix. No inherit complexity introduction via that strategy.

**Comment by berryld1** [comment]
@spgarbet - also, don't know if you saw my edited one above - at first I was puzzled about something that turned out to be the wrong thing - but now I think I am maybe legitimately puzzled that - it would appear - the string "NA"s on the export didn't get coded to true <NA> - my reason for thinking that being they subsequently failed validation again on the import? Based on the documentation, I got the idea invalid values got coded to true <NA>, but maybe I'm misunderstanding.

Is it way too simplistic to have a required argument (i.e., no default value set) to export/import to specify any missing data codes? This can be NULL or empty string if there are none - but it *forces* the user to pay attention to this, because the function will error on missing argument - so, mitigating against the options solution because the user will have to know about it. User might yet fail to set the argument correctly - but that's on the user.

Oh! You could even pass the argument to unlockREDCap(), which would set it globally for that connection, and you don't have to pass the argument each time to import/export.

thoughts?

**Comment by nutterb** [comment]
This is only a partial response. I'm on a break and can take more time to digest everything a little later today.

But we haven't made any changes to the validations in importRecords yet, which is why it is complaining about "NA" values.

Two things: importRecords has an option `returnData` that, when set to true, will terminate the function before calling the API and return the data frame that it has prepared for import.

DataToInspect <- importRecords(rcon, data, returnData=TRUE)

Better yet, though, castForImport is a new function that does validation the same way as exportRecordsTyped. It even returns a validation report as an attribute. The data frame it returns should be ready to pass to importRecords.

That might be useful for you.

I'm assuming, in this, that you aren't trying to submit "NA" as a value to a multiple choice field that doesn't have an "NA" code defined.nim not sure the API will allow that

**Comment by berryld1** [comment]
Thanks, @nutterb 
Super-helpful!
Well, sort of, I'm submitting "NA" to a multple-choice field without that option - except I have NA as a missing data code. 
So, I'm puzzled not so much that importRecords would complain on the way in (expected) - as that, exportRecords already did the complaining on the way out, and I *thought* the upshot of those complaints would be the string "NA" would be coded to true NA, which importRecords does not appear to care about. (For each variable, there are MANY true NAs, but only a few string "NA"s, and importRecords only fussed about the strings.) So, that's where I'm misunderstanding something.
Oh, and it's not the API kicking them out - there's no error - just what importRecords prints to the console, i.e., indices of values that failed validation and "values not imported"

**Comment by nutterb** [comment]
Do I understand correctly that you have a multiple choice field with values x, y, "NA", z, and exportRecordsTyped is leaving the "NA" as is?

**Comment by couthcommander** [comment]
This issue may be a little too complex for me to understand the consequences of a given choice (at some point I'd love to see how @berryld1 is using this). That said I'm generally fine with packages using global options to specify function defaults. It just needs to be well-documented, and the default behaviour should avoid unintended consequences. If you decide to start using package options, it may open up additional benefits (as well as provide the push for a vignette describing those options and encouraging their use).

**Comment by nutterb** [comment]
Do I understand correctly that you have a multiple choice field with values x, y, "NA", z, and exportRecordsTyped is leaving the "NA" as is?

Edit: just reread the entire thread and yes, this is what you said. Twice now. 

This seems like an issue to me and is not what I would have expected. I'll need to Tinker with this and see if I can resolve it

**Comment by berryld1** [comment]
@nutterb - oops, sorry, just saw your edit. :)

**Comment by nutterb** [comment]
Oh, it's definitely me and not you. Still, that illustration is golden. Thank you.

I'm puttering my way across a mountain, so it will be a couple of days before I tackle this

**Comment by berryld1** [comment]
@couthcommander - you know I don't do fancy stuff! @spgarbet made the fatal mistake of asking my opinion on this, which made me a) think of missing data codes and b) read carefully the documentation on exportRecordsTyped, which caused me to realize exportRecordsTyped does not *appear* to be behaving per documentation in its attitude toward missing data codes...
And here we all are! Chatting it up with the Red Queen, Cheshire Cat, Mad Hatter, and such. ;)

**Comment by berryld1** [comment]
@nutterb - no hurry for me! Putter on!

**Comment by nutterb** [comment]
@berryld1 I can't seem to replicate this. Could you try reinstalling `devtools::install_github("vubiostat/redcapAPI")`?  I'm wondering if we quietly fixed this somewhere and it isn't obvious because we haven't incremented the version number recently.

**Comment by spgarbet** [comment]
```
field_types <- c(
  "date_",          "datetime_",  "datetime_seconds_",  "time_mm_ss",
  "time_hh_mm_ss",  "time",       "float",              "number",
  "calc",           "int",        "integer",            "yesno",
  "truefalse",      "checkbox",   "form_complete",      "select",
  "radio",          "dropdown",   "sql")

na_list <- function(FUN)
{
  l <- lapply(field_types, function(f) FUN)
  names(l) <- field_types
  l
}

# Examples
na_list(isNAorBlank)

exportRecordsTyped(rcon, na=na_list(function(x) x=='' | x=='NA' | == 'CBD')))
```

**Comment by berryld1** [comment]
@nutterb 
oh! I wonder if difference in our results could be because the first thing I do after exporting from redcap is: dat <- setDT(dat)[, lapply(.SD, as.character)] because I hate dealing with factors unless I need values to represent some ordinality.
So, am I preserving the NA because I set to character? Maybe not, I guess NA string should already have been set to true NA by the time I set to character...

**Comment by nutterb** [comment]
@berryld1  ... in no particular order

If the SHA hasn't changed, then it seems you had already installed the latest version (it should reinstall now that we've merged new code up). 

Nothing I've tried with your setDT call explains the change. You are correct that the NA should be in place before it creates the factor. Even failing that, when `exportRecordsTyped` tries to cast the factor, it should convert "NA" to an actual NA.  I can't make heads or tails of it.

Unfortunately, this is a point at which I'd normally ask to either watch you work or get access to your code. But there's not way for me to do that without violating a half dozen data security principles. I'll have to turn this over to your internal folks to find a resolution.

**Comment by berryld1** [comment]
@nutterb - thanks so much for looking into it! :)
Not a blocker for me, just a little weird, I'll see if I can even reproduce it!

**Comment by spgarbet** [comment]
@berryld1 If you want schedule some time on my calendar and I can work through it with you.

@nutterb I'll work on a PR for this, name will be na_values.

**Comment by spgarbet** [comment]
The function has been merged. Does this issue need to remain open for the other thread going?

**Comment by spgarbet** [comment]
@nutterb Is there more to do on this one?

**Comment by nutterb** [comment]
I don't think so. The only reason for it to be open still is if we haven't managed to figure out what was going on with @berryld1 's NAs .... I don't remember what it was now, but I think you were going to work with her on it.

**Comment by spgarbet** [comment]
Hm. I'll ask her again. I put in that NA handler fix to deal with it, so I think we're done. I'll confirm with her.

**Comment by spgarbet** [comment]
Looks solved according to user.
