### ISSUE TITLE
exportRecordsTyped assigning erroneous checked/unchecked to checkbox fields with REDCap field choice coded as 0 

### ISSUE THREAD

**Issue by idreamindata** [vubiostat/redcapAPI#199]
This issue was detected when updating code to use exportRecordsTyped over the deprecated exportRecords. It only seems to be happening in checkbox fields when there is a choice that is manually coded as 0. Attached is a REDCap data dictionary/csv example with simulated data that has two checkbox fields with a 0 manually coded choice and one with automatic coding. The same responses were selected for both fields so that we could crosstab to detect the issue. I have also attached a pdf with crosstab results using both exportRecordsTyped and exportRecords. The only crosstab where exportRecordsTyped doesn't match up with exportRecords is for the checkbox field for the 0 coded choice. Happy to provide more documentation if necessary.

[redcapAPI Export Records Checkbox Issues.pdf](https://github.com/vubiostat/redcapAPI/files/12232860/redcapAPI.Export.Records.Checkbox.Issues.pdf)
[Practice_DataDictionary_2023-08-01.csv](https://github.com/vubiostat/redcapAPI/files/12232869/Practice_DataDictionary_2023-08-01.csv)
[Practice_DATA_2023-08-01_1324.csv](https://github.com/vubiostat/redcapAPI/files/12232876/Practice_DATA_2023-08-01_1324.csv)

**Comment by spgarbet** [comment]
The data has "0" in the `checkbox_with_0_choice___0` field for 9 entries. It's being told that "0" means this is checked and that's what it's reporting. This is back to that dual meaning for "0" problem. It's being told it means FALSE and TRUE and the same time.

**Comment by berryld1** [comment]
@spgarbet - this looks like the same problem in reverse (converse?) as was happening with importRecords, where var___0 = 0 was being assigned as checked on the import. So, whatever solution was implemented for import should work on the export, too, yes? For import, where there is a var___0, 0 always means FALSE and 1 always means TRUE; for this case, redcapAPI no longer applies the helpful (except in this case) interpretation that either "1" or the coded value of the checkbox choice means TRUE. Can that be implemented for export as in import?

**Comment by spgarbet** [comment]
Code in question:

https://github.com/vubiostat/redcapAPI/blob/bc1cc475778b6e61c94919066a8094124454e500/R/fieldValidationAndCasting.R#L158-L164

and 

https://github.com/vubiostat/redcapAPI/blob/bc1cc475778b6e61c94919066a8094124454e500/R/fieldValidationAndCasting.R#L211-L226

**Comment by berryld1** [comment]
So, I think, here, we need to except out 0:
coding[this_code_index]

So, like:
coding[this_code_index][coding[this_code_index] != 0]

?

**Comment by berryld1** [comment]
I suppose, for good measure, also:
names(coding)[this_code_index][names(coding)[this_code_index] != 0]

in the event of a 0, 0 coded checkbox option?

**Comment by berryld1** [comment]
@idreamindata - thanks for spotting this!

**Comment by nutterb** [comment]
I think your best short term solution is to use a custom casting function. Something like the following (completely untested, I'm typing this out from my phone. Might be a little buggy)

```
castCheckWithZero <- function(x, field_name, coding){
  if (field_name == "your_field_name"){
    factor(x, 0:1, c("Unchecked", "Checked"))
  } else {
    castChecked(x, field_name, coding)
  }
}
```


The long term solution is....well, read on at your own risk. I'm recording this mostly for my benefit since I probably won't get to look at this for about another week.

@spgarbet and @berryld1 have correctly identified the problem. It's actually a bit easier conceptually than the import problem. With the import, the user could be providing raw, coded, or labelled values, making it rather impossible to automate the solution.

In the export, however, we know that 0 is unchecked and 1 is checked. Always. The reason that we fail to catch it on the export is that we deliberately chose not to use that simplicity in order to support the options for "Unchecked/Checked", coded, or labeled values while also using the same infrastructure we use to cast other multiple choice variables. I still believe that was the right choice, as it makes maintenance and upkeep of the casting set of functions a lot easier.

For that reason, I'm not inclined to rush a solution through; I want to be sure whatever solution we put through plays nicely with that infrastructure.

It might (emphasis might) be possible to intercept the coding construction in getCheckedValue to alter the codings determined for 0 option check fields. I think we would want to add a method `isZeroCodedCheckField` that returns a logical. When TRUE, we could remove the "0" option from `checked_value`

Sidenote: with `isZeroCodedCheckField`, it would also be possible to display a message during import that we found zero coded check fields and the user may want to confirm the results of that import.

**Comment by spgarbet** [comment]
@nutterb Good call. In the midst of figuring it out I forgot we built in the ability to override anything as a workaround for cases like this. This will keep @idreamindata able to work till we get a better solution in place.

**Comment by berryld1** [comment]
Also, cast = raw_cast works?

Here's one from exportRecordsTyped. 0s are coming through.

> with(dat.brca, table(brca_type___0))
brca_type___0
  0   1 
339 267

**Comment by nutterb** [comment]
I think I have this (mostly) working.  There are still some cases where we can't successfully cast values: specifically, casting will fail when we cast from coded or labelled values where the coding or label is "0". 

The good news is, casting from Raw always works, so you will always get the correct value from `exportRecordsTyped`. I just can't guarantee that if you use `castCheckCode` or `castCheckLabel` that any `recastRecords` calls will give the desired result. 

To bring awareness to the issue, I've written in some noise.  Warning will be printed when 

1. a function that attempts to cast data (`exportRecordsTyped`, `recastRecords`, `castForImport`, etc) will issue a warning if zero-coded check fields are identified. The user is advised to verify the result of the casting. The zero-coded fields will be listed.
2. an attempt is made to cast a field that is a zero-coded check field AND a factor AND has any level equal to "0". When this occurs, I'm fairly certain that casting will get tripped up. 

I've drafted the pull request at https://github.com/vubiostat/redcapAPI/pull/205

You're welcome to play with this via `devtools::install_github("vubiostat/redcapAPI", ref = "issue-199-zero-check")`

Feedback on how much noise this makes is appreciated before I formally submit for review.

**Comment by jubilee2** [comment]
Do you plan to release a new version for this issue?

**Comment by spgarbet** [comment]
Soon. CRAN has requested a change due to a roxygen2 change.
