### ISSUE TITLE
User Confusion

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#235]
2 things I am getting emails about from multiple users:

1) In .castRecords_attachInvalid(rcon = rcon, Records = Records, Raw = Raw,  :
  Some records failed validation. See 'invalid' attr.
2) In warnZeroCodedFieldPresent(names(Raw)) :
  Zero-coded check fields found. Verify that casting is correct for

I think for (1) we need to tell them to use `attr(YOUR_OUTPUT_VAR_HERE, `invalid`)` in the warning.

For (2) We need to reference the documentation to something like "see `?exportRecordsTyped`" or something with a longer explanation.

**Comment by nutterb** [comment]
**Regarding 1**

The warning has what I would have thought were clear instructions. But we might be stretching assumptions by assuming users are familiar with attributes and how to retrieve them. When I experimented with the warning, I was trying things like

* Some records failed validation. See 'invalid' attr. (`attr([data.frame], 'invalid')`)
* Some records failed validation. See 'invalid' attr. (e.g., `attr([data.frame], 'invalid')`)
* Some records failed validation. Run `attr([your_data], 'invalid')` to review invalid records

The feel kind of clunky. And I got to thinking....currently, we attach an invalid data.frame to the output _only_ when we detect a failure.  What if we attached the invalid frame every time.  If there are no invalid records, it can just be an empty data frame, and we only issue the warning when we find anything invalid (this has the added benefit that we are returning the same thing every time).  And then, we return the warning

"Some records failed validation. See ?reviewInvalidRecords. 

and then define `reviewInvalidRecords <- function(data) attr(data, "invalid")`

It's a bit convoluted, but I think its a lower entry point of the user's knowledge for the structure of R objects. 

If you're not a fan, we can tinker some with the warning message and should at least put an example in the help files. 

**Item Number the Second**

I've drafted the following and put it into `isZeroCodedCheckField`. It's trivial to add it to the docs for `exportRecordsTyped` and `fieldCastingFunctions`.  The warning can be modified to say 

`Zero-coded check fields found. Verify that casting is correct for [field_name]. See ?exportRecordsTyped

### Zero Coded Check Fields

A zero-coded check field is a field of the REDCap type checkbox that has a coding definition of ⁠0, [label]⁠. When exported, the field names for these fields is ⁠[field_name]___0⁠. As in other checkbox fields, the raw data output returns binary values where 0 represent an unchecked box and 1 represents a checked box. For zero-coded checkboxes, a value of 1 indicates that 0 was selected.

This coding rarely presents a problem when casting from raw values (as is done in exportRecordsTyped). However, casting from coded or labeled values can be problematic, as it can be difficult to determine if a 0 represents a checked or unchecked value. The situations in which casting may fail to produce the desired results are

| Code    | Label     | Result |
|---------|----------|--------|
| 0	      | anything other than "0" | 	Likely to fail when casting from coded values |
| 0	      | 0	                              | Likely to fail when casting from coded or labeled values |

Because of the potential for miscast data, casting functions will issue a warning anytime a zero-coded check field is encountered. A separate warning is issued when a zero-coded check field is cast from coded or labeled values.

When casting from raw or labeled values, it is strongly recommended that the function castCheckForImport() be used. This function permits the user to state explicitly which values should be recognized as checked, avoiding the ambiguity resulting from the coding.

**Comment by spgarbet** [comment]
I love both suggestions. Always attaching something means that logic will be easier, will probably end up deleting some code (good sign). Then making a method to retrieve (getter) for the attr with the directions makes it utterly clear to the user. In both cases they get a piece of code that when executed gives them full details.

I might add in the 2nd paragraph of 'Zero Coded Check Fields': "In this case, it becomes indeterminate from context if the intent of 0 is 'false' or the coded value '0'." I like the imperative use of the function name in the final paragraph. It's compelling the user to take the always correct action.

**Comment by obregos** [comment]
I am receiving more questions about the Zero Coded Check Fields warning. Is there better wording for this warning? Can we add a flag to suppress just this one specific warning? Thoughts?

**Comment by spgarbet** [comment]
`no_warn_zero_coded` ?

@nutterb any objections?

**Comment by nutterb** [comment]
I think I prefer `warn_zero_coded`. Might seem a little silly, but I think it's usually better to name the argument for what it is instead of what it isn't. (I'm sure I'm pretty inconsistent about it)

But I think it's a reasonable idea to let them turn it off if they think they're familiar with the potential pitfalls.

Personally, I'm more concerned that zero-coded checkboxes are that popular :D

**Comment by spgarbet** [comment]
Avoid negative logic in statements, makes everything clearer is a good rule of thumb. With you on the zero coded pitfalls.

**Comment by nutterb** [comment]
I added this topic to the FAQ in https://github.com/vubiostat/redcapAPI/tree/issue-235-checkbox-faq

Might I suggest you merge that into whatever branch you've got working on this?

**Comment by spgarbet** [comment]
@obregos check it out on the current branch.

**Comment by jubilee2** [comment]
> I added this topic to the FAQ in https://github.com/vubiostat/redcapAPI/tree/issue-235-checkbox-faq
> 
> Might I suggest you merge that into whatever branch you've got working on this?

the links not works

**Comment by obregos** [comment]
@jubilee2 I think that link should be pointing here: https://github.com/vubiostat/redcapAPI/blob/main/inst/vignette-source/FAQ.Rmd#L37
