### ISSUE TITLE
Failure on data pull creating record link with no form name

### ISSUE THREAD

**Issue by obregos** [vubiostat/redcapAPI#275]
```
1/6                                 
2/6 [setup]                         
<error/rlang_error>
Error in `tryCatch()`:
! 1 assertions failed:
 * Variable 'form_name': Contains missing values (element 1).
---
Backtrace:
    ▆
 1. └─redcapAPI::exportBulkRecords(...)
 2.   ├─redcapAPI::exportRecordsTyped(conn, forms = j, ...)
 3.   └─redcapAPI:::exportRecordsTyped.redcapApiConnection(...)
 4.     └─redcapAPI:::.castRecords(...)
 5.       └─redcapAPI:::.castRecords_attachInvalid(...)
 6.         ├─redcapAPI:::constructLinkToRedcapForm(...)
 7.         └─redcapAPI:::constructLinkToRedcapForm.redcapApiConnection(...)
 8.           └─checkmate::reportAssertions(coll)
```

**Comment by spgarbet** [comment]
Unfortunately not all rows of data in REDCap are required to have the form name. Occasionally a record will be missing a form_name on export.

**Comment by nutterb** [comment]
> Unfortunately not all rows of data in REDCap are required to have the form name. Occasionally a record will be missing a form_name on export.

Really?  I've never encountered that before. And if true, would make [this line](https://github.com/vubiostat/redcapAPI/blob/main/R/constructLinkToRedcapForm.R#L69) highly problematic.

If you strip out that line, the export will at least proceed without catastrophic failure. I wouldn't expect the link to work, though.

**Comment by spgarbet** [comment]
I've been seeing odd errors where an API call will return an HTTP code of 200 yet have no data or columns missing. I have a suspicion that this is behind it. It should be flagged as an invalid record. I think this might be a root cause. It's not easily reproducible at present and we're still trying to gather information. The proposed strategy right now is we back off and label this as an invalid record (with no link). If it proves to be a an entire block of a batched export, then we may have to put this back in and make it part of the retry loop. I.e., actually check that a valid return came back and not trust the 200 code.
