### ISSUE TITLE
Troubles Getting Data Labels

### ISSUE THREAD

**Issue by userDab33f** [vubiostat/redcapAPI#299]
Hi, 

I am a very novice / untrained coder and have been running into one issue. I used this package to create the RShiny Dashboard that I desire, however the tables that list total counts of each diagnosis or treatment end up showing 'raw' variable names rather than the common names, or 'labels'. (The table shows "variable_name___1", "variable_name___2", rather than "Chocolate", "Vanilla")

I have tried using `rawOrLabelHeaders = 'label' `in `exportRecordsTyped()`, but that doesn't seem to do anything. I have also tried using `config=list(rawOrLabelHeaders = 'label')` under `exportRecordsTyped()`, but that throws the error `Error in f(init, x[[i]]) : is.request(y) is not TRUE`

Like I said, I am by no means a strong coder and could definitely be using these functions wrong, but I would really like to have my final product show the labels instead of the raw variable names!

Best

**Comment by spgarbet** [comment]
`exportRecordsTyped` was created because we needed to make breaking changes in the interface. All the arguments you're mentioning are not supported by `exportRecordsTyped`. Changing the config breaks the way data is converted. To truly understand the new interface I recommend reading `vignette("redcapAPI-best-practices")`. Yes it's long, but there is a lot of control being handed to the user given total control over NA detection, validation that it's good data and finally type (class) conversion into an R object. This is a deep and complex rabbit hole, but is necessary to provide full control of these processing steps to the user. 

What I think you're looking for in the quick fix is the following: `cast=default_cast_no_factor`. If you don't want factors. If you're fine with factors, then try it without any of the mentioned arguments. The default is the label. In general the `cast` argument controls what you're trying to do. 

@nutterb Maybe we could put checks in for old arguments and error out with a message what the new argument would be?

**Comment by nutterb** [comment]
I think @userDab33f  is hitting a different issue, actually.  The field labels are returned in the exported data as an attribute.  The proper way to pull the label would be

```
X <- exportRecordsTyped(rcon)

attributes(X$variable_name___1)
"Chocolate"
```

If you have either `Hmisc` or `labelVector` packages loaded, you can also use `label(X$variable_name___1)`.

**Word of Caution**

Because you are generating count summaries from your data, you should be aware that a lot of operations in R will drop attributes (for instance, if you run this through anything in dplyr). 

You may want to make a reference table of your names and labels before you do any summaries.  This can be done quickly with 

```
library(labelVector)
NameLabelReference <- data.frame(name = names(X), 
                                 label = get_label(X))
```

You should be able to use that reference frame to switch out your names for the labels before you print the data in your shiny UI.

**Comment by userDab33f** [comment]
I would like to use the reference table solution, but it won't work because I have my questions set up as check boxes. When I create a reference table the way you suggest, I get a result like this:

`icecream_flavor     icecream_flavor___1
 icecream_flavor     icecream_flavor___2` 

In other words, the real labels never come in. What I would really need is some way to create one that looked like this: 

` icecream_flavor___1     Chocolate
  icecream_flavor___2     Vanilla` 

The real issue here is that I have my questions set up as checkboxes in REDCap. 

I found a way to get my data into a dataframe that looks like:

`1     Chocolate
 2     Vanilla `

But I am unable to switch the names to adjust my response table. 

Like I said earlier, I am a very inexperienced coder, so I am hoping I am just missing something obvious and easy here. Please let me know if there is something in this package that could help me out.

**Comment by userDab33f** [comment]
`formData <- list("token"=token,
    content='record',
    action='export',
    format='json',
    type='flat',
    csvDelimiter='',
    'fields[0]'='admission_date',
    rawOrLabel='raw',
    rawOrLabelHeaders='label',
    exportCheckboxLabel='true',
    exportSurveyFields='false',
    exportDataAccessGroups='false',
    returnFormat='json'
)
response <- httr::POST(url, body = formData, encode = "form")
result <- httr::content(response)
print(result)`

When using the direct code from REDCap's "API Playground", you are able to adjust `rawOrLabelHeaders` and `exportCheckboxLabel`, is there anywhere in redcapAPI where I can use these functions?

**Comment by nutterb** [comment]
Well, @userDab33f , this is going to be a short term let down.  This is second issue in the past few days that has pointed out that our field labels on checkbox values are not descriptive enough. And the feature that I would like to recommend to you isn't yet available (partially because of that issue). 

I'll work on straightening out these labels in the next couple of days. 

In the meantime....yes, there is a way to make your calls to the API without using our wrappers. The workhorse function underneath all of our API calls is `makeApiCall`, and works pretty similarly to the code you posted above.  The following will get you your basic output

```
response <- makeApiCall(rcon, 
                        body = list(content = "record", 
                                    action = "export", 
                                    format = "csv", 
                                    returnFormat = "csv"))

Rec <- read.csv(text = as.character(response), 
                 na.strings = "")
```

You can add API options to the list in the `body` argument as you please. There is also a helper function `vectorToApiBodyList` that helps format things like the `fields` option

```
response <- makeApiCall(rcon, 
                        body = list(content = "record", 
                                    action = "export", 
                                    format = "csv", 
                                    returnFormat = "csv", 
                                    fields = vectorToApiBodyList(c("field1", "field2"), 
                                                                 "fields")))

Rec <- read.csv(text = as.character(response), 
                 na.strings = "")
```


And lastly, the equivalent call to what you included in your previous comment is as follows (even though it is very similar, we still recommend using `makeApiCall` in order to reduce exposing your token in code)

```
response <- makeApiCall(rcon, 
                        body = list(content='record',
                                    action='export',
                                    format='json',
                                    type='flat',
                                    csvDelimiter='',
                                    fields=vectorToApiBodyList('admission_date',
                                                               "fields"), 
                                    rawOrLabel='raw',
                                    rawOrLabelHeaders='label',
                                    exportCheckboxLabel='true',
                                    exportSurveyFields='false',
                                    exportDataAccessGroups='false',
                                    returnFormat='json'))
```

Hopefully that will keep you going on anything you need short term.  I'm going to work through a couple issues that will give me better tools to help this without having to go this route, and then I'll come back to this.

**Comment by spgarbet** [comment]
> Like I said earlier, I am a very inexperienced coder, so I am hoping I am just missing something obvious and easy here.

No worries about experience. We're here to help and welcome participation by those of all experience levels. If things are not clear on how to do something, I'm of the opinion that the documentation needs clarified. If a function is missing or not correct,  fix it. If it's impossible, outside of scope, or not good practice, explain why and add that to the documentation. Getting feedback from users improves the package at every turn.

**Comment by nutterb** [comment]
Well, that went a lot quicker than I thought it would. 

Please run `devtools::install_local("vubiostat/redcapAPI")` to get the most recent updates. 

With these updates, you should be able to get a mapping with (notice the labels associated with `checkbox_test___x`, etc.). 

```
> Rec <- exportRecordsTyped(rcon, 
+                           fields = "checkbox_test")
> 
> 
> library(labelVector)
> 
> LabelMap <- data.frame(name = names(Rec), 
+                        label = get_label(Rec))
> LabelMap$label <- sub("^.+[(]choice[=]", "", LabelMap$label)
> LabelMap$label <- sub("[)]$", "", LabelMap$label)
> 
> LabelMap
                      name                    label
1                record_id                Record ID
2        redcap_event_name        redcap_event_name
3 redcap_repeat_instrument redcap_repeat_instrument
4   redcap_repeat_instance   redcap_repeat_instance
5 redcap_data_access_group redcap_data_access_group
6        checkbox_test___x                   Guitar
7        checkbox_test___y                  Ukulele
8        checkbox_test___z                 Mandolin
```

**Comment by spgarbet** [comment]
@userDab33f can you confirm if this works for you so we can close out this ticket?

**Comment by nutterb** [comment]
Thanks for bringing it to our attention.  Please let us know if we can help with anything else.
