### ISSUE TITLE
Proposal for importFiles() argument record to accept "new" or other input so that the file gets imported to next/new record

### ISSUE THREAD

**Issue by ajelhajj** [vubiostat/redcapAPI#333]
I am using the importFiles() function and from the documentation I see that “record” is a required input. I was wondering if an option could be added to simply create a new record and import my file to that newest record. 

I ask because in my case, I have created a REDCap project whose only purpose is to store files that I am sending it to from my ETL and don't necessarily have a specific existing record to send it to each time. Thank you!

**Comment by obregos** [comment]
@nutterb or @spgarbet The record is required in the importFiles() call. Could we add a flag to tell importFiles() to create a new record id? Are there any potential issues to add in the functionality?

**Comment by nutterb** [comment]
I'm a little hesitant to build this directly into `importFiles`, mostly due to how compact the function is after it gets past the argument validation. It would also require changing the argument validation to permit `record = NULL`, which could result in a user creating a record when they have simply forgotten to include the record ID. It's also possible I'm being paranoid.

My inclination is to make a separate function, such as `importFileToRecord` with the explicitly documented behavior that if it cannot find the record, or if `record = NULL`, then the record will be created.

One thing to consider is if auto numbering is enabled. If `rcon$projectInformation()$record_autonumbering_enabled` is FALSE, then `record` must be provided. I would think the following would apply

| Autonumbering Enabled | `record = NULL` | Record Exists | Action |
|----------------------------|----------------|-------------------|---------|
| Yes                                   | Yes                 | No                     | Create the record and import the file to the new record (use `force_auto_number = TRUE`)
| Yes                                   | No                 | Yes                     | Import the file to the existing record
| Yes                                   | No                 | No                     | Create the record and import the file to the new record (use `force_auto_number = TRUE`)
| No                                   | Yes                 | No                     | Error: record must be provided when autonumbering is not enabled
| No                                   | No                 | Yes                     | Import the file to the existing record
| No                                   | No                 | No                     | Create the record and import the file to new record (use `force_auto_number = FALSE`)

**Comment by nutterb** [comment]
This is now on the main branch: `devtools::install_github("vubiostat/redcapAPI")`
