### ISSUE TITLE
Export & Execute Data Quality Rules

### ISSUE THREAD

**Issue by rsh52** [vubiostat/redcapAPI#408]
Thank you for all of your work on `redcapAPI`, the new functionality and updated API are very impressive. 

In using `exportDataQuality()` I had assumed it would reference the "Data Quality" rules in the named tool in REDCap, but I see it refers to queries under the "Data Resolution" workflow tool.

Is there a way to retrieve and execute the Data Quality rules themselves either in this package or that you might be aware of through the REDCap API? It would be great to be able to ingest those rules into an R environment and run them on projects for quality validation.

**Comment by couthcommander** [comment]
The short answer is no.

I'm a minor contributor, but have done some thinking about this. It is really confusing that there are "data quality" rules and a "data quality" module (which is actually hidden at our institution). Neither of these are supported through the REDCap API. The module (which is more "data resolution") can be accessed without the API, so we've provided a way to download this data. The REDCap team has not provided a way to download the rules, outside of the web interface. But that doesn't mean it can't be done.

Here's an example

```
pid <- rcon$projectInformation()$project_id
#####
# set these
u <- 'USERNAME'
p <- 'PASSWORD'
redcap_url <- 'https://redcap.vumc.org'
saved_file <- file.path('~', sprintf('dataQualityRules_%s.csv', pid))
#####
body <- list(username = u, password = p, submitted = '1', token = rcon$token)
resp <- redcapAPI:::.curlPost(redcap_url, body, rcon$config)
v <- rcon$version()
dq_url <- sprintf('%s/redcap_v%s/DataQuality/download_dq_rules.php?pid=%s', redcap_url, v, pid)
curl::curl_download(dq_url, saved_file, handle = resp$handle)
```

Given a valid username/password, a CSV file should be downloaded to [saved_file].

We could add the functionality to connect to redcap through username/password, as there may potentially be other uses (functions gained not accessible via API). I suspect the maintainer would reject this as out-of-scope (we support functionality the API supports).

The second part of your question is how to ingest rules and validate a data set. Parsing redcap logic is on our to-do list (#362), but it is a long way from being supported.

**Comment by rsh52** [comment]
Hi @couthcommander thank you for the comprehensive response and apologies for getting back so late.

Appreciate the template for grabbing the rule CSV, could at least be an interim solution for our operations. Would be very interested in the future work of data set validation.

We have line out to the Vanderbilt folks to see if DQ rule exposure is at all possible for the API and will just keep our fingers crossed.

**Comment by spgarbet** [comment]
@obregos implemented the interface we have for Data Quality. Thoughts Savannah?

**Comment by obregos** [comment]
I am in agreement with everything @couthcommander has said.

@rsh52 I am glad that you and others are asking for the DQ rule exposure. We would be happy to implement a function via the API for the Data Quality Rules once that happens. 😊 

Of course, I am open to conversation on implementing a Data Quality Rules functionality, even though, as @couthcommander mentioned, it is likely out of scope because it is not supported by the API. I would be curious if @nutterb had any input/advice on the potential functionality to connect to redcap through username and password. What kind of complications would this introduce, if any?

**Comment by nutterb** [comment]
I, personally, am a bit hesitant to put in functionality that relies on username/password authentication.

1. API token security is already an issue that we are trying to address in the community. While a compromised token is bad, a compromised username/password could be more troublesome on a domain where the REDCap credentials are the same as the EHR credentials. Although I don't bear any actual liability, I would not be comfortable maintaining a tool that exposed that kind of risk. 

2. The use of tokens limits the calls to a project and is integrated with the user permissions relative to data export in that project. Is it possible that user/password could permit a user without API export rights to access data contrary to their user permissions?

3. Thinking of long term maintenance, we have some reasonable expectation of backward compatibility when using the API. Any workaround we use through user/password lacks that expectation.

For these reasons, I lean toward lobbying for including more elements to be included in the API, rather than widely distributing tools that could compromise data security

**Comment by rsh52** [comment]
For what it's worth, I agree that the ideal scenario is that DQ gets added to the API and shouldn't exactly be the responsibility of this package. If anyone here is a part of the REDCap Community page, I posted about this [here](https://redcap.vumc.org/community/post.php?id=237353), but it has yet to generate any discussion.
