### ISSUE TITLE
Functions to deal with REDCap files

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#42]
Use Cases:

(1) REDCap now allows for files associated with a project to have a directory structure. Need routines for this additional functionality. 
(2) The idea to associate R code to share a post transform body of code with all users has been suggested. This would be stored in the directory structure.

https://gist.github.com/couthcommander/e379c7c2c91a40e529052574dd12475c

**Comment by nutterb** [comment]
I've successfully made an adaptation at https://github.com/nutterb/redcapAPI/blob/Issue42-FileRepository/R/exportFileRepositoryListing.R.

**Comment by spgarbet** [comment]
That looks like a wonderful addition.

**Comment by nutterb** [comment]
Having played with this a little bit, I think I'm ready to lay out some design choices and questions. 

## Requests for REDCap

1. Submit a request that an API method be provided to delete a folder from the file repository. (Perhaps REDCap has already addressed why they don't provide this)
2. Would there be any value in requesting that the export file repository list API method have a recursive option?  I think I'd like there to be a native recursive option when exporting the file listing, but I think we can handle the recursion elsewhere.

## Functions

### Definitely to be included

1. `exportFileRepositoryListing` - Returns the listing of files in a directory of the file repository, with option to operate recursively.
2. `exportFromFileRepository` - Downloads and saves a single file from the repository to the local computer
3. importToFileRepository` - Loads a single file from the local computer into the file repository. Requires that a folder_id be provided.
4. `deleteFromFileRepository` - Deletes a single file from the file repository
5. `createFileRepositoryFolder` - Creates a folder in the file repository. requires that a parent folder be provided (defaulting to top-level)

### Optionally included

Please indicate if any of these are of interest or value for development now, later, or not at all.

1. `exportFileRepository` - Downloads and saves all of the files within a folder in the repository to the local computer, with an option to operate recursively.
2. `importFileRepository` - Loads a complete folder from the local computer into the file repository, with an option to operate recursively.
3. `deleteFileRepository` - Deletes all of the files within a folder in the file repository, with an option to operate recursively

## Function Design Specification

### exportFileRepositoryListing

**Arguments**

* rcon - redcapApiConnection
* folder_id - numeric of length 0 or 1. The folder ID for which the listing is downloaded. If length 0, use the top-level directory
* recursive - logical(1). If TRUE, search through and return listing of all subfolders

**Return**

Returns a data.frame of four columns: folder_id, doc_id, name, parent_folder. (note: parent folder is added by redcapAPI and is not provided by REDCap. It is the ID number of the folder in which the folder/file resides).

When there are no files/folders found, the data frame has zero rows, but the same structure.

**Questions**

* the API throws an error if doc_id does not exist or the user does not have access to the document. How should this be handled in redcapAPI? 
    + I propose capturing the error and recasting as a warnign while returning an empty data frame.
    + This behavior could be overridden by setting error_handling = "error", forcing an error instead.

### exportFromFileRepository

exports a single file from the file repository

**Arguments**

* rcon - redcapApiConnection
* doc_id - numeric(1). The document ID to be downloaded
* dir - character(1). A directory on the local system to which the file is to be saved. Defaults to the working directory. 
* create - logical(1). Create the directory in `dir` if it does not already exist. Defaults to FALSE. If `dir` does not exist and `create = FALSE`, an error is thrown.

**Return**

Prints a message indicating what file was saved and to where it was saved.

### importToFileRepository

**Arguments**

* rcon - redcapApiConnection
* file - character(1) a file on the local system to be saved in the file repository.
* folder_id - numeric of length 0 or 1. If length 0, use the top level directory. This is the directory in the file repository to which the file will be saved.

**Return**

Prints a message indicating what file was imported and the directory path to which it was saved.

### deleteFromFileRepository

**Arguments**

* rcon - redcapApiConnection
* doc_id - numeric(1). The document ID of the file to be deleted from the File Repository. 

**Return**

Return a message providing the filepath of the deleted file. 

If doc_id doesn't exist in REDCap, it may be necessary to handle the error to gracefully return a message that no such file exists. Behavior of this could be managed by error_handling.

### createFileRepositoryFolder

**Arguments**

* rcon - redcapApiConnection
* name - character(1) with no more than 150 characters. The name of the folder to create.
* folder_id - character(0/1). If length 0, create the folder in the top level directory. Otherwise, create it in the folder indicated.
* dag_id - numeric(0/1). If of length one, access to the file will be limited to those in the indicated DAG. Otherwise, all users have access.
* role_id - numeric(0/1). If of length one, access to the file will be limited to those in the indicated role. Otherwise, all users have access.

**Return**

Return a message with the folder_id of the new folder, its full path, and its DAG and Role restrictions.

If we choose to cache the file repository, it would be prudent to follow up after the import and see if rcon has a cached file repository and refresh it if it does.  ie

```
if (rcon$has_fileRepository()){
  rcon$refresh_fileRepository()
}
```

**Testing**

I think we will want to exclude this from unit testing for now. There is not method to delete a folder from the repository. To include this in the tests would add a new folder every time tests are run. That seems kind of cluttered to me.

### exportFileRepository

This would be an extension of `exportFromFileRepository` that allows for exporting all of the files in a directory with one call.

**Arguments**

* rcon - redcapApiConnection
* folder_id - character(0/1). The folder of files to download. If length 0, defaults to the top-level directory. 
* dir - character(1). A directory on the local system to which the file is to be saved. Defaults to the working directory. 
* create - logical(1). Create the directory in `dir` if it does not already exist. Defaults to FALSE. If `dir` does not exist and `create = FALSE`, an error is thrown.
* recursive - logical(1). If TRUE, export all subfolders and their files as well

**Return**

Returns a message giving the location of the saved files, the number of folders, and number of files downloaded (including dir).

**Note**

Error handling is important on this one. If there is an attempt to download a file to which the user doesn't have access, we may want to skip it and also return a number of files skipped for lack of access. Then again, this may be a non-issue. I don't know if we'd even get inaccessible files from exportFileRepositoryListing.

### importFileRepository 

An extension of both importToFileRepository and createFileRepositoryFolder. This would allow for the user to import all the files in a local directory into the File Repository, with an option for recursive behavior.

**Arguments**

* rcon - redcapApiConnection
* dir - character(1) a folder on the local system with the files to be saved in the file repository.
* folder_id - numeric of length 0 or 1. If length 0, use the top level directory. This is the directory in the file repository to which the file will be saved.
* recursive - logical(1). If TRUE, files in all subfolders will be imported as well. Any directories in the local folder will be created on the File Repository.

**Return**

Returns data frame giving the folders and files saved to the file repository (likely retrieved via a call to exportFileRepositoryListing after the import is complete)

### deleteFileRepository

An extension of deleteFromFileRepository that allows for deletion of multiple files in one call.

**Arguments**

* rcon - redcapApiConnection
* folder_id - numeric(1) OR the value 'top-level'. Provides the folder ID from which files will be deleted. The use of an additional character value here is out of the ordinary, but I worry what may happen if someone carelessly calls this without specifying a folder_id and we assume the top-level as we do in other File Repository methods. Doing it this way at least gives us confidence that they truly intended top-level deletion.
* recursive - logical(1). If TRUE, files in all subfolders will be deleted as well. Note: the API does not provide a way to delete folders; only the files will be deleted.

**Return**

A data.frame of files deleted from the respository. This could be obtained by a call to exportFileRepositoryListing on folder_id prior to executing the deletion.

## Other Tools

* `serializeFileForImport` - a function to convert a file to the byte string needed for import. (I've not fully specified this function as I'm not entirely sure what will be needed until we start working this into the API)
* `reconstituteFileFromExport` - a function to extract a byte string from a response and save it to a file. (I've not fully specified this function as I'm not sure what will be needed to extract the byte string and save to a file)
* Note: These previous two functions could also be used to support exportFiles and importFiles, and so their development should be sensitive to the needs of those methods.
* `FILE_REPOSITORY_EMPTY_FRAME` a data.frame in `constants.R` that can be used to when an empty data frame is needed.

## Other Questions

1. Should the import and delete methods have an additional argument such as `confirm = c("ask", "no", "yes")`?  
    + ask: a pop-up asks the user to confirm the action
    + no: exit the function with no action
    + yes: execute the function without user confirmation (useful for automated scripts)
2. `exportFromFileRepository` and `exportFileRepository` are awfully similar names. Is there a better naming convention we can use that distinguishes one file behavior from multiple file behavior?

**Comment by couthcommander** [comment]
This is nice, thanks @nutterb! One thing I'll mention - in my testing sometimes REDCap would attribute the creator to another user. This user does have access but doesn't use the API. If I spend some more time with this, I'll check in with the REDCap folks, but you might watch for it too.

**Comment by nutterb** [comment]
Yes, we can.
