### ISSUE TITLE
repeatedInstrument functions / wide data format output [post process records]

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#44]
The repeated instrument is a relatively new function of REDCap. It would be nice if support functions for this existed that returned data in a wide format. One user is using pivotWider as a post process to make this happen.

**Comment by omair-a-khan** [comment]
I'm not sure if this is helpful in any way, but I wanted to drop some code to give an example of how I'm using pivot_wider to deal with a repeated instruments issue we had to code around. To give some background, there are 15 variables (med01_name ~ med15_name) that are part of a repeated instrument in our collaborator's REDCap project. If more than 15 medication names need to be recorded for a certain participant within a certain redcap_event_name, the API outputs a dataframe with as many rows necessary with just these 15 variables populated as needed. In order for us to get this data into a wider format so that there is one row per participant per event from the longitudinal, repeated instruments project, I artificially created new variables programmatically that contain these values using the following code:

```
relevant.var <- grep("^med\\d+_name$", names(data), v = T)
max_vars_in_data.int <- gsub('med|name|_', '', relevant.var) |> as.numeric() |> max()
max_chars_in_digits.int <- gsub('med|name|_', '', relevant.var) |> nchar() |> max()

questionnaires_03.df <- questionnaires_02.df |>
  group_by(pid, redcap_event_name, redcap_repeat_instrument) |>
  mutate(
    temp_multiplier_plus1.int = row_number(),
    .before = "pid"
  ) |>
  tidyr::pivot_wider(
    names_from = temp_multiplier_plus1.int,
    values_from = matches("^med\\d+_name$"),
    names_glue = "med{formatC(as.numeric(gsub('med|name|_', '', .value)) + (max_vars_in_data.int * (as.numeric(temp_multiplier_plus1.int) - 1)), width = max_chars_in_digits.int, flag = '0')}_name"
  ) |>
  ungroup()
```

Thus, if there are, for example, a maximum of 54 medication names for a certain participant in the data (which will be pulled from the API over 4 rows), this code will create 60 (= 15 + (15 * 4-1)) variable names (med01_name ~ med60_name) that will be populated with the medication names, the rest being filled with NA. (Btw, to make this work, the input dataframe, `questionnaires_02.df`, needs to have been processed to only include rows where variable `redcap_repeat_instrument` is non-missing and only contains the name of the relevant repeated instrument. Afterwards, the resulting dataframe will need to be merged back into a dataframe where the value for `redcap_repeat_instrument` is missing and does not have any columns that follow the regex pattern `^med\\d+_name$`).

Obviously, this is a very niche situation, but perhaps it gives the development team an idea of how users of the API are post-processing repeated measures data so that we can create a dataset that can be used for analytical purposes. It would be awesome if you guys could come up with a general solution that can help users create a dataset that can be easily used for analysis, perhaps with the use of some helper functions or arguments.

**Comment by spgarbet** [comment]
This is helpful.

**Comment by spgarbet** [comment]
Let's call this one `widerRepeated`

**Comment by spgarbet** [comment]
Internal review has decided "dropRepeatedNA" is dangerous to data and should not be used. Savannah and Lynne have a revised design that matches the users goals. The code from that previous merge needs pulled out as part of this ticket to finish it out.

**Comment by spgarbet** [comment]
Here's what I have proposed on #106 : https://gist.github.com/spgarbet/650b88332ca867e3f0ec087f31cc59e5

**Comment by spgarbet** [comment]
I'm reading further through the code. I have 2 questions:

```
  # set everything as character in data and data dictionary and assign id.temp to data
  dat <- data.frame(lapply(Records, as.character), stringsAsFactors = FALSE)
```

Why strip everything back to character? This defeats all the casting and possible earlier post processing of exportRecordsTyped. 

Secondly, the "invalid" attribute if it exists on the Records, needs to be reattached to the resulting data.frame.

**Comment by spgarbet** [comment]
widenRepeated will ignore form data that is not a repeated instance. Let's start with the simplest case, instead of expecting raw data input, it expects a single form's worth of rows. If that form is not repeating it simple returns what it was passed.

While the raw data looks like this: 
```
> head(tmp)
  id.tmp redcap_event_name redcap_repeat_instrument redcap_repeat_instance
1      1     event_1_arm_1     repeating_instrument                      1
2      1     event_1_arm_1     repeating_instrument                      2
3      1     event_1_arm_1                                                
4     10     event_1_arm_1                                                
5     11     event_1_arm_1                                                
6     12     event_1_arm_1                                                
  repeat_question_1     repeat_datetime
1              Good 2023-04-20 13:34:00
2               Bad 2023-04-20 13:35:00
3              <NA>                <NA>
4              <NA>                <NA>
5              <NA>                <NA>
6              <NA>                <NA>
...
```
The function widenRepeated will check if it's a single consistent form's worth of data and error out if it is not provided this.

What it expects is like the following:
```

> tmp
  id.tmp redcap_event_name redcap_repeat_instrument redcap_repeat_instance
1      1     event_1_arm_1     repeating_instrument                      1
2      1     event_1_arm_1     repeating_instrument                      2
  repeat_question_1     repeat_datetime
1              Good 2023-04-20 13:34:00
2               Bad 2023-04-20 13:35:00
```

This is the data for the single form 'repeating_instrument` which can now be made "wide"

```
> reshape(tmp, direction="wide", idvar="id.tmp", timevar="redcap_repeat_instance", v.names=c("repeat_question_1", "repeat_datetime"))
 id.tmp redcap_event_name redcap_repeat_instrument repeat_question_1.1
1      1     event_1_arm_1     repeating_instrument                Good
    repeat_datetime.1 repeat_question_1.2   repeat_datetime.2
1 2023-04-20 13:34:00                 Bad 2023-04-20 13:35:00
```

**Comment by spgarbet** [comment]
Great work!
