### ISSUE TITLE
Delete Records

### ISSUE THREAD

**Issue by spgarbet** [vubiostat/redcapAPI#9]
User has reported that delete records does not work. Need to investigate.

**Comment by nutterb** [comment]
I believe the problem here is at https://github.com/vubiostat/redcapAPI/blob/main/R/deleteRecords.R#L76. The API doesn't accept parameters formatted this way. (This same problem will pop up in various functions). 

In my unfinished work, I've rewritten this function and it uses a separate method to build the parameter lists (see https://github.com/nutterb/redcapAPI/blob/reworked/R/deleteRecords.R#L82, which references https://github.com/nutterb/redcapAPI/blob/reworked/R/vectorToApiBodyList.R).

**Comment by spgarbet** [comment]
Okay, I can take this over the finish line.

**Comment by spgarbet** [comment]
I can't seem to reproduce the problem on the main branch. Delete is working for me just fine. My attempted patch in the branch seems to break things. I did add the helper function referenced and then delete stopped working.

**Comment by nutterb** [comment]
Does the main branch work with more than one record?

**Comment by spgarbet** [comment]
I'll rework the test case to do that and we'll see. It doesn't work post fix at all, but maybe it just needs a bit more syntax.

**Comment by nutterb** [comment]
I think it would have worked without these lines (https://github.com/vubiostat/redcapAPI/blob/delete-records-9/R/deleteRecords.R#L98-L100).  Not sure the arms will work though.  I submitted a pull request that I think will be pretty robust (at least for records and arms)

**Comment by spgarbet** [comment]
> deleteRecords(rcon, c("delete.me", "delete.too"))
 Error in deleteRecords(rcon, c("delete.me", "delete.too")) : 
1 assertions failed:
* Variable 'vector': Must be of type 'atomic', not 'list'.

**Comment by spgarbet** [comment]
I accidentally pushed up NA records and now the date conversion code is failing. So a new test case is identified for the date conversions. Issue #6

**Comment by spgarbet** [comment]
This works for me now. Can we get a test case for the arms you mentioned?

**Comment by spgarbet** [comment]
I noticed a typo in the dealing with the arms portion. I will write a test case that exposes it, then fix.
